# Generated by Django 3.1.2 on 2021-01-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('objet', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='docs_file/')),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
