# Generated by Django 3.1.2 on 2020-12-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_bulletin', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Laissez ce champ vide', unique=True)),
                ('img_bulletin', models.ImageField(upload_to='bulletin_img/')),
                ('content_bulletin', models.TextField()),
                ('numero_bulletin', models.IntegerField()),
                ('total_enfant_scolarise', models.IntegerField(blank=True)),
                ('enfants_scolarise_filles', models.IntegerField(blank=True)),
                ('enfants_formation_professionnelle', models.IntegerField(blank=True, help_text='orientés et accompagnés en formation professionnelle ', null=True)),
                ('enfants_formation_professionnelle_filles', models.IntegerField(blank=True, help_text='orientés et accompagnés en formation professionnelle ', null=True)),
                ('enfants_jeunes_adultes', models.IntegerField(blank=True, help_text='enfants, jeunes et adultes contactés lors de la descente sur le terrain ', null=True)),
                ('nombre_enfants_identifies', models.IntegerField(blank=True, help_text='Uniquement les chiffres', null=True)),
                ('nombre_contacts', models.IntegerField(blank=True, help_text='Uniquement les chiffres', null=True)),
                ('nombre_entretiens_realises', models.IntegerField(blank=True, help_text='Uniquement les chiffres', null=True)),
                ('nombre_suivi_familial', models.IntegerField(blank=True, help_text='Uniquement les chiffres', null=True)),
                ('nombre_enquetes_realises', models.IntegerField(blank=True, help_text='Uniquement les chiffres', null=True)),
                ('nombre_suivi_scolarise', models.IntegerField(blank=True, help_text='Uniquement les chiffres', null=True)),
                ('nombre_suivi_formations_professionnelles', models.IntegerField(blank=True, help_text='Uniquement les chiffres', null=True)),
                ('nombre_animations_rue', models.IntegerField(blank=True, help_text='Uniquement les chiffres', null=True)),
                ('nombre_reinsertions_familiales', models.IntegerField(blank=True, help_text='Uniquement les chiffres', null=True)),
                ('editeur', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
