# Generated by Django 3.1.2 on 2021-01-30 09:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_auto_20210130_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='numero_bulletin',
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='content_bulletin',
            field=tinymce.models.HTMLField(),
        ),
    ]
