# Generated by Django 3.1.2 on 2021-02-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0006_auto_20210130_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='enfants_formation_professionnelle',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='enfants_formation_professionnelle_filles',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='enfants_jeunes_adultes',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='enfants_scolarise_filles',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='nombre_animations_rue',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='nombre_contacts',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='nombre_enfants_identifies',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='nombre_enquetes_realises',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='nombre_entretiens_realises',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='nombre_reinsertions_familiales',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='nombre_suivi_familial',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='nombre_suivi_formations_professionnelles',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='nombre_suivi_scolarise',
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='total_enfant_scolarise',
        ),
    ]
