# Generated by Django 3.1.2 on 2020-12-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenenement',
            name='titre_evenement',
            field=models.CharField(max_length=300),
        ),
    ]
