# Generated by Django 3.1.2 on 2021-02-02 06:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0002_auto_20201220_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenenement',
            name='content_evenement',
            field=tinymce.models.HTMLField(verbose_name='content_evenement'),
        ),
    ]
