# Generated by Django 3.1.2 on 2021-02-02 06:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='content_formation',
            field=tinymce.models.HTMLField(verbose_name='content_formation'),
        ),
    ]
